### PR TITLE
Update GEOS source to 3.11.3

### PR DESCRIPTION
**Pull request by vladaburian**
Fixes compilation error with clang 16 and gcc 13 (missing 'cstdint' header).

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Ah, the failure is on our end. Another MSRV was increased. I'll add the `Cargo.lock` file to this project as well and fix the failures.

**Comment by GuillaumeGomez** [comment]
Can you rebase please?

**Comment by GuillaumeGomez** [comment]
Thanks!

**Comment by vladaburian** [comment]
I thank you! I'm surprised how swift it was :)

**Comment by GuillaumeGomez** [comment]
Why would you want it to be more difficult? 😅

**Pull request merged**
