### PR TITLE
Update libgeos source to 3.12.1

### PR DESCRIPTION
**Pull request by weiznich**

### CODE REVIEW

**Comment by lnicola** [comment]
Can you also update https://github.com/georust/geos?tab=readme-ov-file#static-build?

**Review by lnicola — APPROVED** [review]

**Comment by weiznich** [comment]
I'm not sure what needs to be done to address the failing CI builds.

**Comment by lnicola** [comment]
Not sure either, but they were failing before.

**Comment by GuillaumeGomez** [comment]
Thanks! Do you want a new release?

**Comment by weiznich** [comment]
I personally do not need a timely release, but given that others are affected (see #127) that might be welcome for them.

**Comment by jayvdb** [comment]
I would appreciate a new release of geos-src

**Comment by jayvdb** [comment]
Much appreciated!

**Pull request merged**
