### PR TITLE
Removed unnecessary lifetimes

### PR DESCRIPTION
**Pull request by ManeraKai**
Fixes https://github.com/georust/geos/issues/152 and `2) Lifetimes` part of https://github.com/georust/geos/issues/141

### CODE REVIEW

**Comment by kylebarron** [comment]
I haven't fully read through the diff yet but this looks awesome and I'm really excited for this. (With the caveat that I don't know C FFI well enough to know if there's any relation between removing named lifetimes and FFI safety). In [geoarrow-rs](https://github.com/geoarrow/geoarrow-rs) I've struggled around GEOS lifetimes a decent amount with conversions to/from geoarrow.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Looks good to me, thanks a lot! Please run `cargo fmt`. You can ignore the memory leaks failures in the CI.

**Comment by GuillaumeGomez** [comment]
Gonna make a new release "soon".

**Comment by ManeraKai** [comment]
We are using geos for a university project. Please maoe it more "soon"

**Comment by michaelkirk** [comment]
If it's really so urgent you can [patch](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section) your dependency.

**Comment by GuillaumeGomez** [comment]
> We are using geos for a university project. Please make it more "soon".

For faster things, you can sponsor me. Otherwise, please be patient or follow @michaelkirk great advice.

**Comment by ManeraKai** [comment]
Alright.

**Comment by GuillaumeGomez** [comment]
Released the new `9.0.0` version.

**Pull request merged**
